# Created with YamlCreate.ps1 v2.2.0 $debug=NVS1.CRLF.5-1-19041-1682.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: Helix.Helix
PackageVersion: 22.08.1
PackageLocale: en-US
Publisher: Helix
PublisherUrl: https://helix-editor.com/
# PublisherSupportUrl: https://github.com/helix-editor/helix
# PrivacyUrl:
# Author: Helix
PackageName: Helix
PackageUrl: https://helix-editor.com/
License: MPL-2.0
LicenseUrl: https://github.com/helix-editor/helix/blob/master/LICENSE
# Copyright:
# CopyrightUrl:
ShortDescription: A post-modern modal text editor.
# Description:
Moniker: helix
Tags:
- editor
# Agreements:
# ReleaseNotes:
# ReleaseNotesUrl: https://github.com/helix-editor/helix/releases/tag/22.08.1
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.4.0
